site_name: 知屿
site_description: 知识与好资源的收藏小岛

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: indigo
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 资源库: resources/index.md
  - 电子锐评: reviews/index.md
  - 伤害计算: damage/index.html

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
