site_name: 知屿
site_description: 知识与好资源的收藏小岛

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: white
    accent: blue
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 资源库: resources/index.md

extra_css:
  - stylesheets/extra.css
