name: 发布 MkDocs 网站

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 下载网站源文件
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 安装 MkDocs 和 Material 主题
        run: pip install mkdocs-material

      - name: 构建网站
        run: mkdocs build --strict

      - name: 发布到 gh-pages 分支
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
